export function getRandomPG13Prompt() {
  return prompts[Math.floor(Math.random() * prompts.length)];
}

const prompts = [
  "A good way to get kicked out of a K-Pop concert",
  "A great name to have on a fake driver's license",
  "A weird thing for the letters in your alphabet soup to suddenly spell out",
  "A great prank to play on a pizza delivery guy",
  "The most surprising thing you could find in the glove box of a rental car",
  "Four-leaf clovers are lucky. But if you find a five-leaf clover...",
  "The only job you would do for free",
  "If you can\u2019t say anything nice...",
  "Little-known fact: In a lifetime, the average person will _________ over 1,000 times while sleeping",
  "You should always wear a helmet when _________",
  "Where would you live if you were two inches tall?",
  "What to do when a really tall person sits in front of you at the movie theater",
  "The absolute best place to hide your house key",
  "A strange place to go to while wearing a ski mask",
  "What those giant Easter Island heads are thinking",
  "So, how do you like it?",
  "You would gladly give money to someone on the street if they asked \u201cCan you spare some change so I can _________?\u201d",
  "You know you\u2019re a spoiled brat when your tree house has a _________",
  "The big conspiracy that nobody even suspects is _________",
  "How Jonah passed the time stuck inside a giant fish",
  "The title of the most popular TV show in North Korea, probably",
  "Where the missing sock in the dryer ends up going",
  "The worst part about being seven feet tall",
  "A really weird protest sign would be \u201cEnd _________ Now!\u201d",
  "How you can tell your new, all-vegetable diet is working",
  "The name of a band in which every member plays the spoons",
  "A little-known use for ear wax",
  "The type of life they\u2019ll probably find on Mars",
  "The name of a board game for players age 70 & older ",
  "Bob the Builder probably wouldn\u2019t be as popular with children if he were Bob the _________",
  "The worst thing to do when a bear is right next to you",
  "Unlike \u201cMaverick\u201d or \u201cIceman,\u201d a really bad Air Force fighter pilot name would be _________",
  "It would\u2019ve been a much different movie if instead of \u201cPhone home,\u201d E.T. kept saying, \u201c_________\u201d",
  "A weird way to dry your hair",
  "A new name for the U.S. Congress ",
  "What Adam thought when he first met Eve",
  "What do ceramic garden gnomes do at night?",
  "The real secret to a happy marriage is...",
  "A rejected name for the game Yahtzee",
  "The best thing to blurt out in order to ruin a beautiful sunset",
  "You know you\u2019re comfortable in a relationship when you ask your significant other to _________",
  "The best line to say when you come out of a 10-year coma ",
  "The best name to give an ugly baby",
  "The first thing Abraham Lincoln would do if he came back from the dead",
  "Come up with a <i>TMZ</i> celebrity headline from five years in the future",
  "What the roller coaster attendant is actually saying during his mumbled preamble before the ride",
  "The most annoying person in a movie theater would _________",
  "A terrible sign-off line for a newscaster",
  "A good sign that you may be a ghost",
  "The creepiest thing to whisper in somebody\u2019s ear as you\u2019re hugging them",
  "A better name for the ukulele",
  "What the Queen\u2019s Guard is secretly thinking as they just stand there",
  "The worst part about having a mustache",
  "An awkward thing to hear from the person pooping in the bathroom stall next to you",
  "A quick way to save money on grocery bills",
  "How they really select the next Pope",
  "The name of a new cologne inspired by celebrity chef Guy Fieri",
  "A great way to quickly get out of credit card debt",
  "The worst upstairs neighbors would be people that _________",
  "The weirdest message your cat could write out to you in its litter box",
  "A horrible pick-up line",
  "The best way to keep a co-worker from stealing your lunch",
  "The worst thing to find when you move into a new house",
  "The worst carnival prize you could win",
  "The only thing worse than standing in a really long line is standing in a really long line for _________",
  "You wake up 100 years in the future and are shocked to find _________",
  "A weird thing for a preacher to say to end every sermon",
  "A rejected tourism slogan for Des Moines, Iowa: \u201cHome of the _________\u201d",
  "A forgotten book in the classic Harry Potter series: <i>Harry Potter and the _________</i>",
  "The weirdest thing a restroom attendant could offer you",
  "The worst Thanksgiving Day balloon would be a giant, inflatable _________",
  "The big, crazy twist at the end of the next M. Night Shamalayan movie: He was _________ the whole time!",
  "Most people know it as The Big Apple, but a lesser-known nickname for New York is The Big _________",
  "The next best thing to chew when you\u2019re out of gum",
  "You know you\u2019re in a very weird fast food restaurant when the cashier asks, \u201cDo you want _________ with that?\u201d",
  "It\u2019s incredibly rude to _________ with your mouth open",
  "You never have a _________ when you need one",
  "In the next big sports scandal, we\u2019ll find out that _________",
  "Worse than global warming, the real threat to humanity is global _________",
  "Forget dogs. What is really man\u2019s best friend?",
  "How you can tell it\u2019s a doctor\u2019s first day on the job",
  "The worst name for an all-girl band",
  "A bad thing to say to your date\u2019s parents",
  "The worst song to do pairs figure skating to",
  "What landed you in the emergency room this time?",
  "The worst thing to say during a job interview",
  "A magazine category that hasn\u2019t been invented yet",
  "The top 3 ingredients in garbage truck juice",
  "A really bad superhero power",
  "The worst thing to put on a pizza",
  "If evolution is true, then why hasn\u2019t _________ evolved into _________?",
  "The worst possible choice for the person on the new $20 bill",
  "A little-known lyric in the original draft of the \u201cStar-Spangled Banner\u201d",
  "The best thing to shoot out of a cannon",
  "The winners on <i>The Bachelor</i> get a rose. The losers should get _________",
  "The title of a never-released Jimmy Buffett song",
  "The worst thing to hear from your GPS: \u201cIn two miles, _________\u201d",
  "The weirdest sentence a judge could impose",
  "A good use for toenail clippings",
  "A fitting punishment for people who double-dip their chips",
  "America\u2019s energy crisis would be over if we made cars that ran on _________",
  "Something it\u2019d be fun to watch ride an escalator ",
  "A high school superlative you don\u2019t want to win: Most Likely To _________",
  "A rejected title for <i>Moby Dick</i>",
  "Something you do not want to find under your hotel bed",
  "You know your doctor has gone insane when he tells you to make sure you _________ at least once a day",
  "A sign that your kid isn\u2019t good at sports",
  "The first sign that you\u2019re no longer cool",
  "A surprising thing to find stuck to the bottom of your shoe",
  "The worst thing that could follow \u201cHoney-Roasted\u201d",
  "Why are geese such jerks?",
  "A sign that you\u2019re a bad teacher",
  "What bears dream about all winter",
  "A good sign that you\u2019ve drunk too much Mt. Dew",
  "The manliest way to start a conversation",
  "What the abominable snowman does when he\u2019s bored",
  "A good alternative for ping-pong paddles",
  "You know you\u2019re a chocoholic when...",
  "The worst reason to use a time machine",
  "Something you should not do while crowdsurfing",
  "What those bolts in Frankenstein\u2019s neck are for",
  "What Waldo from \u201cWhere\u2019s Waldo?\u201d says to himself in the mirror",
  "The worst road trip would start with someone _________",
  "A creepy thing to write in your email signature line",
  "The only five words in your obituary in the newspaper",
  "What\u2019s the U.S. government really hiding in Area 51?",
  "The worst advice an IT guy could give",
  "A really bad name for an apartment complex: \u201c_________ Place\u201d",
  "What should we do with all of that plastic that won\u2019t disintegrate?",
  "One thing that the rich truly enjoy is diamond-encrusted _________",
  "The best part of turning 100 years old",
  "The lesser-known other way to find the Wizard of Oz: Follow the _________ Road",
  "Forget coffee. Don\u2019t talk to me until I\u2019ve had my _________",
  "Odd new shampoo instructions: \u201cLather, Rinse, _________, Repeat.\u201d",
  "The worst magic trick",
  "The lost Hemingway book: <i>The Old Man and the _________</i>",
  "The title of a podcast you would never ever listen to",
  "The name of a new, terrifying species of spider",
  "The most annoying co-worker would constantly _________",
  "A surefire way to ruin Christmas",
  "The name of the worst baby doll",
  "\u201cDon\u2019t blame me, I voted for _________.\u201d",
  "The name of a fast food restaurant in the Stone Age",
  "Dodgeball would be an even better sport if _________ were allowed",
  "A _________ a day keeps the doctor away",
  "Instead of \u201cCheese!\u201d the worst family photographer would tell you to say, \u201c_________!\u201d",
  "The title of a college admission essay that would definitely get rejected",
  "Something Big Bird will confess on his deathbed",
  "The last thing you\u2019d want to find in your air ducts",
  "A terrible name for a dragon",
  "The worst way to unclog a toilet",
  "Something that\u2019s been hiding in the background in every episode of <i>Friends</i>",
  "What\u2019s really destroying the ozone layer?",
  "You know you\u2019re famous when...",
  "The absolute worst moment for a bird to poop on you",
  "A weird thing for someone to frame and hang on the wall",
  "What you don\u2019t want to hear from the passenger next to you at the start of a 20-hour flight",
  "Why ducks really fly south in the winter",
  "What a frog would say to his psychiatrist",
  "The worst theme for your kid\u2019s first dance recital",
  "The worst combination of two actors that could possibly star in the next season of <i>True Detective</i> together",
  "It\u2019s disappointing to put together a 1,000 piece puzzle and realize it\u2019s just a picture of _________",
  "The name of a law firm you shouldn\u2019t hire",
  "The worst thing to find frozen in an ice cube",
  "Something you don\u2019t expect to see when you spy on your neighbors",
  "An experiment mice actually like having performed on them",
  "A double rainbow doesn\u2019t have gold at the end of it. Instead, it has _________",
  "The best shirt to wear next to somebody who\u2019s wearing an \u201cI\u2019m with stupid\u201d T-shirt",
  "The worst thing a plastic surgeon could say after he botched your surgery: \u201cI\u2019m sorry, I accidentally _________\u201d",
  "The worst advice your boxing coach could give you",
  "What an alarm clock could say that would wake you right up",
  "A weird thing to hear from your doctor: \u201cI\u2019m afraid you have _________\u201d",
  "In a shocking poll, it was discovered that three out of four Americans _________",
  "The most common thing you\u2019d hear if you could read people\u2019s thoughts",
  "A realistic, honest fast-food slogan",
  "A good sign that you\u2019ve drunk too much Mt. Dew",
  "What bears dream about all winter",
  "The worst breakfast: pancakes shaped like _________",
  "A sign that you\u2019re a bad teacher",
  "If a genie gives you three wishes, the best things to wish for are: 1) a billion dollars, 2) eternal life, and 3) _________",
  "The futuristic invention you can\u2019t wait to see exist",
  "What\u2019s really at the center of the Earth?",
  "Safety tip! Don\u2019t eat a half hour before you _________",
  "The real way you can tell an alligator from a crocodile",
  "Survival tip! Start a fire by rubbing _________",
  "Helpful advice you would give to Super Mario",
  "In the future, scientists discover that the secret to eternal youth is _________",
  "Something you shouldn\u2019t use a chainsaw for",
  "A surprising purchase on Willy Wonka\u2019s credit card statement",
  "A really stupid idea for a phone app (that would still make you millions of dollars)",
  "The name of a new game show that sounds terrible",
  "The one thing you wish a politician would just say already",
  "A secret way to get stubborn ketchup out of the bottle",
  "Something you promise to yell if you win this game",
  "A creepy thing to find scribbled onto a dollar bill",
  "If you don\u2019t have extra money, an odd thing to use as a tip for your waiter",
  "A sure sign that a drifter has been secretly living in your house",
  "The one thing that isn\u2019t better dipped in chocolate",
  "A terrible vacation idea: going to visit The Museum of _________",
  "A great gag gift would be an exploding _________",
  "A surprising thing to hear in a nature documentary",
  "The years 2016-2024 will be remembered as \u201cThe _________ Age\u201d",
  "Little-known fact: the scariest animal in the world is the _________ cobra",
  "A bad name for a brand of hot sauce",
  "An excuse to avoid riding the mechanical bull",
  "The worst warning to read on some medicine you just swallowed",
  "The name of a really bizarre diet that just never caught on",
  "A ridiculous government agency that no one knows about: The Department of _________",
  "The best thing about being thrown into a volcano",
  "The world\u2019s most boring video game",
  'New requirement at amusement parks: \u201cYou must be this _________ to ride"',
  "You probably shouldn\u2019t hire a moving company called _________",
  "The weirdest combination of three items that you could buy at the store",
  "The most obnoxious name someone could give their kid",
  "Something that is probably on Nicolas Cage\u2019s \u201cTo Do\u201d list",
  "HR would probably get the most complaints on \u201cBring your _________ to work\u201d day",
  "A Socrates quote that nobody bothered to write down",
  "Why is the sky blue?",
  "The best way to catch a leprechaun",
  "The worst things to juggle",
  "Turns out, the meaning of life is _________",
  "The worst tattoo to have on your forehead",
  "A weird photo to keep in your wallet",
  "An odd painting to hang above your bed",
  "A poor substitute for a necktie",
  "The perfect day off is just twelve straight hours of _________",
  "Something awful to hold in your mouth for an hour",
  "A great way to start a conversation with a weird loner on the subway",
  "A hip, new advertising slogan for socks",
  "The least appetizing name for a restaurant",
  "A bad name for a hospital",
  "Something you do not want to do while standing in a police lineup",
  "After the Heimlich Maneuver, the second-best way to stop someone from choking",
  "A rejected safety technique for when you catch fire was to \u201cstop, drop, and _________\u201d",
  "The weirdest room you could see in an airport would be one specifically designated for _________",
  "If you really want to impress the Olympic diving judges, try a dive that involves _________",
  "What you think the word \u201cpandiculation\u201d means",
  "A body of water you definitely shouldn\u2019t swim in",
  "Something fun to ask the old wise man on top of the mountain",
  "How would YOU fix the economy?",
  "The hardest part about living in a submarine",
  "If you really, really love something, let it _________",
  "The name of the music playlist that will definitely put an end to the party",
  "A bad name for a water park",
  "A polite way to say \u201cbooger\u201d",
  "Kennedy\u2019s original speech said, \u201cAsk not what your country can do for you, ask _________\u201d",
  "What the hot trend in weddings will be in the year 2046",
  "Something fun to scream at a farmer\u2019s market",
  "Mother Teresa\u2019s deepest secret ",
  "The most creative thing you can make entirely out of boogers",
  "An ill-advised outfit to wear to your first day at a new job",
  "Sleepwalking can be a problem but it\u2019s not as bad as sleep_________",
  "What to do when your parachute fails",
  "Something people used to do for fun before electricity",
  "The most embarrassing crime to get caught committing",
  "The name that cavemen probably gave to diarrhea",
  "The worst person to share a hot tub with",
  "A peculiar thing to see in a Help Wanted ad would be \u201cHelp Wanted: _________\u201d",
  "A real weirdo would fall asleep to the sounds of _________",
  "The name of a dog food brand you probably should not buy",
  "Come up with a name for a generic brand of hot dogs that you probably shouldn\u2019t buy",
  "Everything tastes better with _________",
  "Life hack! Lower your heating bills by...",
  "The worst thing that could crawl out of your toilet",
  "The worst advice a doctor could give",
  "Something a weatherman might yell if he completely snapped during the weather forecast",
  "A great birthday present for your worst enemy",
  "No one would guess this is where the treasure is buried",
  "The secret to a healthy head of hair",
  "A strange thing to read on a door mat",
  "The secret to a great marriage",
  "What really happens if you stare at the sun too long",
  "A prank the Supreme Court Justices probably play on each other",
  "What the Easter Bunny does with his free time",
  "A little known-perk of being U.S. president",
  "A word that should be in the dictionary but isn\u2019t",
  "A really odd thing to say on your deathbed",
  "The Four Horsemen wouldn\u2019t be as scary if they were the Four _________men of the Apocalypse",
  "It\u2019s illegal to yell \u201cFire!\u201d in a crowded theater, but it should also be illegal to yell, \u201c_________!\u201d",
  "A good name for a pet cemetery",
  "A new word for people that drive too slow in the fast lane",
  "The perfect name for a second head that sprouts on your shoulder",
  "The worst material from which to make a pair of pajamas",
  "Queen Elizabeth\u2019s deepest, darkest secret",
  "Come up with a slogan for the Russian Tourism Board",
  "The best part about being Donald Trump",
  "Sometimes John Travolta wildly mispronounces names. How might he wildly mispronounce his own name?",
  "The worst toy store: Build-A-_________ Workshop",
  "The weirdest thing you can buy at the Vatican gift shop",
  "The worst invention that starts with \u201cSpray-On\u201d",
  "The name of a species of dinosaur you wouldn\u2019t want to meet",
  "Something overheard at the Last Supper",
  "Something you can make out of body hair",
  "So... what was that movie <i>Birdman</i> about anyway?",
  "A great pet name for a parasitic worm that lives in your ear",
  "Little-known fact: Over the course of a lifetime, an average person accidentally eats ten _________",
  "Something you probably shouldn\u2019t try to sell on eBay",
  "The worst air freshener scent",
  "A terrible thing to sign on the cast of your friend\u2019s broken leg",
  "A sign you probably shouldn\u2019t put up in your yard",
  "A bad title for a self-help book",
  "An unusual \u201cSpecial Skill\u201d to include on your resume",
  "What kittens would say if they could talk",
  "A strange thing to keep as a pet",
  "The worst thing about Canada",
  "You should never share _________ with someone else",
  "The grossest thing you could find at the bottom of a swimming pool",
  "The sound a tree actually makes when it falls and no one is around to hear it",
  "You need three things to live: food, water, and _________",
  "A good use for toenail clippings",
  "What you would do with two free hours and a flamethrower",
  "The worst name for an SUV",
  "New sport idea: professional _________",
  "Trash talk you would hear at a chess meet",
  "Something you shouldn\u2019t stuff with cheese",
  "Something pirates probably aren\u2019t very good at",
  "Everyone knows there\u2019s no such thing as _________",
  "A completely untrue rumor about Alvin from Alvin and the Chipmunks",
  "You should never _________ and _________ at the same time",
  "The worst thing about being a billionaire",
  "Briefly describe your imaginary friend",
  "What you call a baby sasquatch",
  "What is a tree thinking all day?",
  "The best use for a leftover meatball",
  "A bad reason to call 911",
  "The best way to quickly blow a million dollars",
  "Your first decree after being named Supreme Ruler of Earth",
  "The worst thing to receive for trick-or-treat",
  "Come up with a name for a kooky ostrich who solves mysteries",
  "A phrase you would love to hear Morgan Freeman say",
  "USA! USA! America is still number one in...",
  "An Olympic sport that never made it: Synchronized _________",
  "The government should legalize...",
  "The first thing to do if you\u2019re attacked by a shark",
  "The worst thing to find growing on your neck",
  "A little-known fact about the Jolly Green Giant",
  "The perfect meal would be a _________ stuffed in a _________ stuffed in a _________",
  "What\u2019s black and white and red all over?",
  "It never ends well when you mix _________ and _________",
  "Invent a silly British term for pooping",
  "The best reason to go to Australia",
  "The beauty pageant no one wants to see: Miss _________",
  "The most boring graffiti you could see in the subway",
  "A slogan to get everyone excited about corn",
  "You never forget your first _________",
  "Little-known fact: The human body is approximately 80% _________",
  "Something you shouldn\u2019t buy at a yard sale",
  "If we only use 10% of our brains, what\u2019s the other 90% doing?",
  "What you want your gravestone to read",
  "The worst menu item that starts with \u201cAll You Can Eat\u201d",
  "A sign you wouldn\u2019t want to see at a seafood restaurant",
  "Something fun to yell during an opera",
  "A group activity at a really bad summer camp",
  "The worst ringtone for a cell phone",
  "A great nickname for your armpit hair",
  "\u201cKnock, knock!\u201d \u201cWho\u2019s there?\u201d _________",
  "A Tweet from a caveman",
  "A message found in a bottle floating in the sea",
  "The worst car feature that ends with \u201cholder\u201d",
  "What Chewbacca has really been yelling all these years",
  "The most stereotypical country song title",
  "The best way to survive a bear attack is _________",
  "The worst name for a funeral home",
  "The worst name for a rap artist",
  "Something that should never be \u201chomemade\u201d",
  "Another use for marshmallows",
  "Another use for gravy",
  "A great way to cure the hiccups",
  "An animal Noah shouldn\u2019t have saved",
  "The biggest secret the government keeps",
  "Something you wouldn\u2019t expect a Ouija board to say",
  "The best way to defeat terrorism is...",
  "The best way to tell if a tomato is ripe",
  "Come up with a name for a sitcom about a bunch of wacky nuns",
  "The best way to scare a burglar",
  "The worst thing to yell while a professional golfer putts",
  "The second thing said on the moon",
  "Something you can only do in a Walmart if no one\u2019s looking",
  "A name for a really cheap hotel",
  "The worst name for a mountain",
  "The best thing about being really dumb",
  "The real secret to living to age 100",
  "What really happens if you tear off that mattress tag",
  "A bad first line for your presidential inauguration speech",
  "A fun thing to do with a bowl of pudding",
  "Another use for cooked spaghetti",
  "A weird physical way to greet someone",
  "The worst name for a tanning salon",
  "The worst word that can come before \u201cfart\u201d",
  "A bad substitute for a toothbrush",
  "A trick you shouldn\u2019t teach your dog",
  "The worst material with which to make a snowman",
  "A terrible sportscaster catchphrase for when somebody dunks a basketball",
  "The first thing a pig would say if it could talk",
  "A surprising job entry on Abraham Lincoln\u2019s resume",
  "Something you\u2019d yell to heckle the performing dolphins at Sea World",
  "The worst name for a \u201cbig and tall\u201d store",
  "A new name for kumquats",
  "The worst thing to wear to your court trial",
  "A rejected crayon color",
  "Graffiti you might find in a kindergarten",
  "The first sign that you\u2019re old",
  "The worst question to ask during a White House tour",
  "Bad advice for new graduates",
  "The best way to tell if someone is dead",
  "What you hope the Mars Rover finds",
  "Where missing socks go",
  "A rejected phrase for one of those Valentine heart candies",
  "Something that will get you thrown out of a Wendy\u2019s",
  "It would be scary to read on a food package, \u201cMay contain trace elements of _________.\u201d",
  "A just-so-crazy-it\u2019s-brilliant business idea to pitch on <i>Shark Tank</i>",
  "A terrifying fortune cookie fortune",
  "Something the devil is afraid of",
  "CBS should air a TV show about lawyers who are also _________",
  "A great thing to yell before jumping out of an airplane",
  "A better name for the game Duck Duck Goose",
  "A bad way to remove unsightly chest hair",
  "An unusual theme for a kid\u2019s lunchbox",
  "What the government is hiding from the public in Area 497",
  "What your pancreas tests revealed",
  "A bad, one-word slogan for a presidential campaign",
  "Something you'd make a butler do the moment you hired him",
  "Why did the mortician cross the road?",
  "Something you should never try to heat in the microwave ",
  "A surprising thing to find inside a piñata ",
  "An alternate name for The Mona Lisa",
  "A reason to travel back in time to two weeks ago",
  "If you\u2019d never heard the term \u201cgreat white shark,\u201d what might you call it when you saw one for the first time?",
  "A place where you're not likely to spot Bigfoot",
  "Something you should never say as the captain of a bowling team",
  "The dumbest person in the history of all time ",
  "Another name for the Grand Canyon",
  "Another name for Canada",
  "A bad use for clam chowder",
  '"On the 147th day of Christmas, my true love gave to me..."',
  "The best name for an obese rapper",
  "A good puck replacement if they run out of pucks in a game of hockey",
  "If animals took over, an exhibit you\u2019d see at the human zoo",
  "A terrible wedding gift",
  "A street name you never see",
  "The first thing that pops into your mind right now",
  "A weapon that should be added to the game Clue",
  "The toy surprise in an Unhappy Meal",
  "Make up a word for the watery substances that come out of a ketchup bottle when you first squeeze it",
  "Make up a name for the space between your nostrils",
  "The worst theme for a pinball machine",
  "Something you don't want to find in your Christmas stocking",
  "A title of a self-help book for rats",
  "The worst thing you could rub all over your face",
  "Something you rarely see used as a car decoration",
  "A historical event that would make a bad theme for a restaurant",
  "The worst thing to try to sell door-to-door",
  "Something you probably shouldn\u2019t bring on a trip across the Sahara desert",
  "What's that stain?",
  "Something you'd love to smash with a wrecking ball",
  "A bad name for a pet goldfish",
  "Life would be so much better if we all lived in _________",
  "Something it\u2019s not a good idea to put in the overhead bin on an airplane",
  "A weird thing for a bank robber to demand in a hostage situation",
  "Something they will probably never make a series of commemorative stamps for",
  "A club you wish they had in high school",
  "A strange place to hold a family reunion",
  "Something you\u2019d sneak into space, if you were an astronaut",
  "The name of that cheese shop you\u2019re going to open some day",
  "The liquid that would make for the worst salad dressing",
  "An unusual motif for a baby\u2019s nursery",
  "A terrible name to have if you\u2019re running for public office",
  "Four out of five dentists agree you should never _________",
  "Something that would make a creepy replacement for the horses on a merry-go-round",
  "The worst thing to vomit into when you suddenly need to vomit",
  "Make up a word that means \u201cto make up a word\u201d",
  "Like Plutonium or Einsteinium, what would you name the next Periodic Table element they discover?",
  "A bad name for a pirate",
  "Something fun to scream when you win in a game of bingo, other than \u201cBingo!\u201d",
  "A movie that should never be made into a theme park ride",
  "A business or service that shouldn't have a drive-through window",
  "The worst flavor for a sno-cone",
  "Combine any two words to make a fun, new made-up word",
  "A lesser-known ingredient in most microwave pizza pockets",
  "A great place to hide an Easter egg",
  "A trick you\u2019d like to see a poodle do",
  "A better name for the Washington Monument",
  "You never know when you\u2019re going to need insurance. You could wake up tomorrow and _________",
  "The worst thing to overhear during your surgery",
  "A bad name for a brand of bottled water",
  "How do you like it?",
  "Come up with a new dessert that contains the name of a U.S. state",
  "A terrible food truck would be one that goes around selling only _________",
  "A reason to get into a fist fight with a koala bear ",
  "Little-known fact: the fourth Wise Man gave baby Jesus the worst gift of all: _________ ",
  "A theme for a desk calendar that wouldn\u2019t sell very well ",
  "The worst thing you could stick in a toaster ",
  "The worst Halloween costume for a young child",
  "\u201cThis just in! A _________ has won the election and will become the new governor of Texas.\u201d ",
  "A better name for the human bladder",
  "Surprising first words for your baby to speak",
  "A good name for a dog country singer",
  "A lawn decoration sure to make the neighbors mad",
  "The worst thing to say when trying to adopt a pet",
  "Fun thing to do if locked in the mall overnight",
  "The worst person to receive a sponge bath from",
  "People wouldn\u2019t respect He-Man as much if, to gain his power, he held up his sword and shouted \u201c____________________\u201d",
  "Pants would be a whole lot better if they _________",
  "A little-known way to get gum out of your hair",
  "The most awesome Guinness World Record to break",
  "It\u2019s bad to be buried alive. It\u2019s worse to be buried alive with _________.",
  "Something that would not work as well as skis",
  "What to say to get out of jury duty",
  "Little-known fact: The government allows peanut butter to contain up to 10% _________",
  "A good sign that your house is haunted",
  "A bad occupation for a robot to have",
  "A sequel to the painting \u201cDogs Playing Poker\u201d",
  "The Tooth Fairy\u2019s other job",
  "A birthday present you shouldn\u2019t get for your grandmother",
  "What time is it?",
  "Invent a Christmas tradition sure to catch on",
  "A short motto everyone should live by",
  "The best way to start your day",
  "The worst name for a summer camp",
  "The first commandment in the new religion you started",
  "Three things are certain in life: Death, Taxes, and _________",
  "Something that\u2019s made worse by adding cheese",
  "The perfect song to hum on the toilet",
  "A word that should never follow \u201cBeef\u201d",
  "Something that is currently legal that should be banned",
  "Come up with a name for a rock band made up entirely of baby ducks",
  "We can all agree that _________",
  "Something you shouldn\u2019t buy off of Craigslist",
  "A bad thing to say to a cop as he writes you a speeding ticket",
  "How far is too far?",
  "If at first you don\u2019t succeed...",
  "The name you would give to a really mopey pig",
  "Something you\u2019d be surprised to see come out of a pimple you pop",
  "Today\u2019s music needs more _________",
  "The best question to ask God when you meet him",
  "A fun trick to play on your doctor",
  "A bad campaign slogan for a congressperson",
  "A unique way to escape from prison",
  "The title of a new YouTube cat video that\u2019s sure to go viral",
  "Come up with the name of a country that doesn\u2019t exist",
  "The best way to keep warm on a cold winter night",
  "The real reason the dinosaurs died",
  "Something you should never put on an open wound",
  "The name of a font nobody would ever use",
  "The best thing about going to prison",
  "The best title for a new national anthem for the USA",
  "A college major you don\u2019t see at many universities",
  "What would make baseball more entertaining to watch?",
  "A little-known fact about Canada",
  "Name a TV drama that\u2019s about a vampire doctor",
  "What\u2019s actually causing global warming?",
  "The first thing you would do after winning the lottery",
  "A name for a really bad Broadway musical",
  "On your wedding night, it would be horrible to find out that the person you married is _________",
  "The Skittles flavor that just missed the cut",
  "A terrible name for a cruise ship",
  "What\u2019s the Mona Lisa smiling about?",
  "The crime you would commit if you could get away with it",
  "Something squirrels probably do when no one is looking",
  "Something you shouldn\u2019t get your significant other for Valentine\u2019s Day",
  "A dangerous thing to do while driving",
  "The best thing about living in an igloo",
  "Using only two words, a new state motto for Texas",
  "Something you shouldn\u2019t wear to a job interview",
  "The name of the reindeer Santa didn\u2019t pick to pull his sleigh",
  "What\u2019s the first thing you would do if you could time travel?",
  "What would you do if you were left alone in the White House for an hour?",
  "Come up with the name of book that would sell a million copies, immediately",
  "A not-very-scary name for a pirate",
  "The name of a pizza place you should never order from",
  "Something you should never use as a scarf",
  "The worst words to say for the opening of a eulogy at a funeral",
  "Come up with a really bad TV show that starts with \u201cBaby\u201d",
  "A great way to kill time at work",
  "What\u2019s wrong with these kids today?",
  "Come up with a really bad football penalty that begins with \u201cIntentional\u201d",
  "You know you\u2019re in for a bad taxi ride when _________",
  "The terrible fate of the snowman Olaf in a director\u2019s cut of <i>Frozen</i>",
  "Sometimes, after a long day, you just need to _________",
  "Give me one good reason why I shouldn\u2019t spank you right now",
  "The best pick-up line for an elderly singles mixer",
  "The best news you could get today",
  "Invent a holiday that you think everyone would enjoy",
  "Usually, it\u2019s bacon, lettuce and tomato, but come up with a BLT you wouldn\u2019t want to eat",
  "The worst thing you could stuff a bed mattress with",
  "A great opening line to start a conversation with a stranger at a party",
  "Something you would like to fill a swimming pool with",
  "If you were allowed to name someone else\u2019s baby any weird thing you wanted, what would you name it?",
  "Okay... fine! What do YOU want to talk about then?!!!",
  "A good fake name to use when checking into a hotel",
  "A vanity license plate a jerk in an expensive car would get",
  "The name of a canine comedy club with puppy stand-up comedians",
  "What\u2019s lurking under your bed when you sleep?",
  "Come up with a name for the most difficult yoga pose known to mankind",
  "One place a finger shouldn\u2019t go",
  "The worst job title that starts with \u201cAssistant\u201d",
  "The grossest thing you\u2019d put in your mouth for $18",
  "The last person you\u2019d consider inviting to your birthday party",
  "Where do you think the beef really is?",
  "A fun trick to play on the Pope",
  "Write a newspaper headline that will really catch people\u2019s attention",
  "Something it\u2019d be fun to throw off the Eiffel Tower",
  "Name the eighth dwarf, who got cut at the last minute",
  "A good place to hide boogers",
  "Come up with a catchier, more marketable name for the Bible",
  "The best thing to use when you\u2019re out of toilet paper",
  "A good way to get fired",
  "The most presidential name you can think of (that isn\u2019t already the name of a president)",
  "Something you should never say to your mother",
  "Where\u2019s the best place to hide from the shadow monsters?",
  "The three ingredients in the worst smoothie ever",
  "Something that would make an awful hat",
  "How many monkeys is too many monkeys?",
  "Something you\u2019d be surprised to see a donkey do",
  "The title you\u2019d come up with if you were writing the Olympics theme song",
  "Name the sequel to <i>Titanic</i> if there were one. <i>Titanic 2: _________</i>",
  "An alternate use for a banana",
  "What you\u2019d guess is an unadvertised ingredient in most hot dogs",
  "An inappropriate thing to do at a cemetery",
  "Like chicken fingers or chicken poppers, a new appetizer name for your fun, theme restaurant: chicken _____",
  "Thing you\u2019d be most surprised to have a dentist find in your mouth",
  "If God has a sense of humor, he welcomes people to heaven by saying, \u201c_________\u201d",
  "Something that would not work well as a dip for tortilla chips",
  "Who let the dogs out?",
  "What do vegans taste like?",
  "Make up a word that describes the sound of farting into a bowl of mac & cheese",
  "A new ice cream flavor that no one would ever order",
  "What John Goodman\u2019s belches smell like",
  "The name of a new perfume by Betty White",
  "One thing never to do on a first date",
    "The most embarrassing name for a dog",
  "The worst thing you could discover in your burrito",
  "Something you\u2019d probably find a lot of in God\u2019s refrigerator",
  "Brand name of a bottled water sold in the land of Oz",
  "The worst family secret that could come out over Thanksgiving dinner",
  "A fun thing to yell as a baby is being born",
  "A terrible theme for a high school prom",
  "A more environment-friendly alternative to toilet paper",
  "What tattoo should Justin Bieber get next?",
  "What do kittens dream of?",
  "What makes hot dogs taste so good?",
  "A better name for France",
  "The worst thing to find stuck in your teeth",
  "The worst excuse for showing up late to work",
  "The worst thing for an evil witch to turn you into",
  "Everyone knows that monkeys hate _________",
  "The secret to a happy life",
  "You would never go on a roller coaster called _________",
  "What two words would passengers never want to hear a pilot say?",
  "The worst name for a race horse",
  "You shouldn\u2019t get a massage at a place called _________",
  "The least romantic place to propose marriage",
];
